[package]
name = "ral-registers"
version = "0.1.3"
authors = ["Adam Greig <adam@adamgreig.com>"]
edition = "2018"
description = "MMIO registers abstraction with a macro API"
repository = "https://github.com/adamgreig/ral-registers"
license = "MIT OR Apache-2.0"
keywords = ["mmio", "embedded"]
categories = ["embedded", "no-std"]
autoexamples = false

[dependencies]

[dev-dependencies]
stm32ral = { version = "0.5.0", features = ["stm32f0x0"] }
